### ISSUE TITLE
JSTwister not started

### ISSUE THREAD

**Issue by stijnvanderlaan** [jstwister/public#2]
I do not get the plugin to work, I get the message:
`JSTwister not started, starting it... We'll let you know when it's done(hold tight, might take a few mins)`

In the Developer Tools I get:

```
An unknown error occurred. Please consult the log for more details.
e.onUnexpectedError @ shell.ts:443
(anonymous) @ shell.ts:403
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:139
t.onUnexpectedExtHostError @ mainThreadErrors.ts:13
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

I wait, but nothing is happening.

Version: 0.0.9

**Comment by gcazaciuc** [comment]
Can you also please have a look at Output => JSTwister Console and see whats going on ? Does it persist after ide restart?

**Comment by stijnvanderlaan** [comment]
Ah! I was looking for that:

```
[JSTwister Core] - fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.<anonymous> (/Users/worm/.vscode/extensions/jstwister.jstwister-0.0.9/jstwister-core/jstwister.js:2160:6)
    at __webpack_require__ (/Users/worm/.vscode/extensions/jstwister.jstwister-0.0.9/jstwister-core/jstwister.js:34:30)
    at Object.module.exports.name (/Users/worm/.vscode/extensions/jstwister.jstwister-0.0.9/jstwister-core/jstwister.js:64549:16)
    at __webpack_require__ (/Users/worm/.vscode/extensions/jstwister.jstwister-0.0.9/jstwister-core/jstwister.js:34:30)
    at Object.<anonymous> (/Users/worm/.vscode/extensions/jstwister.jstwister-0.0.9/jstwister-core/jstwister.js:64315:18)
    at __webpack_require__ (/Users/worm/.vscode/extensions/jstwister.jstwister-0.0.9/jstwister-core/jstwister.js:34:30)
    at Object.<anonymous> (/Users/worm/.vscode/extensions/jstwister.jstwister-0.0.9/jstwister-core/jstwister.js:63726:17)
    at __webpack_require__ (/Users/worm/.vscode/extensions/jstwister.jstwister-0.0.9/jstwister-core/jstwister.js:34:30)

[JSTwister Core] - Exited with code 1
```
It does persist after ide restart.

**Comment by stijnvanderlaan** [comment]
Creating the /logs directory seems to help

**Comment by gcazaciuc** [comment]
Should be fixed on latest version
